### ISSUE TITLE
Can't use nohup to start a jar

### ISSUE THREAD

**Issue by HarryWu-CHN** [camunda/camunda-platform-get-started#85]
I use `mvn package` to package the java code to jar. The jar can directly be used by the command below
```bash
java -jar camunda-cloud-get-started-java-jar-with-dependencies.jar
```

However, when I use nohup, it can't start or automatic show it has done in one second.
```bash
nohup java -jar camunda-cloud-get-started-java-jar-with-dependencies.jar &
[1]+  Done                    nohup java -jar camunda-cloud-get-started-java-jar-with-dependencies.jar
```

So, what should I do to start a **worker** backstage? Thank you.

**Comment by HarryWu-CHN** [comment]
I realize that `waitUntilSystemInput` is causing the problem, so is there any other way to block?

Mayby there is another way that can run in the background.

**Comment by menski** [comment]
This repository is meant to show the usage of the Zeebe worker, but not as a production usage code. In production applications you will not want to block the main thread. For an easy get started have a look at https://github.com/camunda-community-hub/spring-zeebe.
